server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

clients:
  products:
    base-url: http://localhost:3001
    timeout-ms: 1000

logging:
  level:
    com.similarproducts: INFO

resilience4j:
  circuitbreaker:
    instances:
      similarIds:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 1000ms
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s
      productById:
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 1000ms
        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 5s

  timelimiter:
    instances:
      similarIds:
        timeout-duration: 2s
        cancel-running-future: true
      productById:
        timeout-duration: 1s
        cancel-running-future: true