server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

clients:
  products:
    base-url: http://localhost:3001
    timeout-ms: 3000

logging:
  level:
    com.similarproducts: INFO
