server:
  port: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

clients:
  products:
    base-url: http://localhost:3001
    timeout-ms: 500
